#!/usr/bin/env python3
"""
Coordination-mode comparison for the DISTRIBUTED Context-Fabric arm:
LF centralized RTI coordination vs decentralized (STP/peer-to-peer).

Identical federation (one replica per robot + all-to-all proposal mesh + gossip);
only the LF coordination mode differs. Shows that the N=16 "frontier" is a
centralized-RTI artifact: decentralized coordination removes the per-tag barrier
and the distributed arm scales clean to N=16.

Reads each arm's report.py aggregate:
    <centralized>/testbed_metrics_agg.csv   (LF coordination: centralized)
    <decentralized>/testbed_metrics_agg.csv  (LF coordination: decentralized)

Writes:
    results/coord_comparison.md / .tex
    figures/testbed/coord_compare.{pdf,png}   (T_claim on a log axis -- the
                                                blow-up spans ~3 orders of magnitude)
"""

import argparse
import csv
import os

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))


def load_agg(d):
    path = os.path.join(d, "testbed_metrics_agg.csv")
    if not os.path.exists(path):
        raise SystemExit(f"missing aggregate: {path}")
    rows = {}
    with open(path) as f:
        for r in csv.DictReader(f):
            n = int(float(r["num_robots"]))
            rows[n] = {k: (float(v) if v not in ("", None) else 0.0)
                       for k, v in r.items() if k != "num_robots"}
    return rows


def pm(mean, sd, prec=2):
    return f"{mean:.{prec}f} ± {sd:.{prec}f}" if sd and sd > 0 else f"{mean:.{prec}f}"


def write_markdown(ns, cen, dec, out):
    path = os.path.join(out, "coord_comparison.md")
    L = ["# Distributed arm: centralized-RTI vs decentralized LF coordination", "",
         "Same federation (one coordinator replica per robot, all-to-all proposal mesh, "
         "gossip); only the LF coordination mode differs. Mean ± sd across seeds.", "",
         "| N | coordination | Completion | Throughput (tasks/min) | T_claim (ms) | Util |",
         "|---|---|---|---|---|---|"]

    def row(n, label, s):
        return (f"| {n} | {label} | {pm(s['completion_rate_mean'], s['completion_rate_sd'])} | "
                f"{pm(60*s['throughput_tps_mean'], 60*s['throughput_tps_sd'], 2)} | "
                f"{pm(s['t_claim_ms_mean_mean'], s['t_claim_ms_mean_sd'], 1)} | "
                f"{pm(s['agent_utilization_mean'], s['agent_utilization_sd'])} |")

    for n in ns:
        L.append(row(n, "centralized RTI", cen[n]))
        L.append(row(n, "decentralized", dec[n]))

    # find the frontier N where centralized collapses
    bad = [n for n in ns if cen[n]["t_claim_ms_mean_mean"] >= 500 or cen[n]["completion_rate_mean"] < 0.5]
    L += ["", "## What it shows",
          "- Identical federation; the only change is `coordination: centralized` -> "
          "`decentralized` (federates advance on their own clock via an `STP_offset` and "
          "exchange proposals peer-to-peer; the RTI only does startup/clock-sync)."]
    for n in bad:
        L.append(
            f"- **At N={n}, centralized RTI collapses** (completion "
            f"{cen[n]['completion_rate_mean']:.0%}, T_claim {cen[n]['t_claim_ms_mean_mean']:.0f} ms): "
            f"every federate's tag advance is gated by an all-to-all barrier the single RTI cannot "
            f"keep up with. **Decentralized scales clean** (completion "
            f"{dec[n]['completion_rate_mean']:.0%}, T_claim {dec[n]['t_claim_ms_mean_mean']:.1f} ms, "
            f"RTI idle).")
    L += ["- So the N=16 \"frontier\" was a property of the **centralized coordination mode**, not "
          "of the distributed architecture: peer-to-peer coordination removes it and the distributed "
          "Context-Fabric scales to N=16."]
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    return path


def write_latex(ns, cen, dec, out):
    path = os.path.join(out, "coord_comparison.tex")
    L = ["% Auto-generated by scripts/compare_coord.py -- paste into the thesis.",
         r"\begin{table}[ht]", r"    \centering", r"    \small",
         r"    \renewcommand{\arraystretch}{1.15}", r"    \setlength{\tabcolsep}{5pt}",
         r"    \begin{tabular}{rl ccc}", r"        \hline",
         r"        $N$ & LF coord. & Compl. (\%) & $T_{\text{claim}}$ (ms) & Util. (\%) \\",
         r"        \hline"]

    def row(n, label, s):
        return (f"        {n} & {label} & "
                f"{pm(100*s['completion_rate_mean'], 100*s['completion_rate_sd'], 0)} & "
                f"{pm(s['t_claim_ms_mean_mean'], s['t_claim_ms_mean_sd'], 1)} & "
                f"{pm(100*s['agent_utilization_mean'], 100*s['agent_utilization_sd'], 0)} "
                r"\\").replace("±", r"$\pm$")

    for n in ns:
        L.append(row(n, "central", cen[n]))
        L.append(row(n, "decentral", dec[n]))
        if n != ns[-1]:
            L.append(r"        \hline")
    L += [r"        \hline", r"    \end{tabular}",
          r"    \caption[Centralized vs decentralized LF coordination]{Distributed Context-Fabric "
          r"under centralized-RTI vs decentralized LF coordination (identical federation). "
          r"Centralized coordination's all-to-all barrier collapses at $N{=}16$; decentralized "
          r"peer-to-peer coordination scales clean.}",
          r"    \label{tab:coord_modes}", r"\end{table}"]
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    return path


def make_figure(ns, cen, dec, figs):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as e:
        print(f"  [figure skipped: matplotlib unavailable: {e}]")
        return []
    os.makedirs(figs, exist_ok=True)
    plt.rcParams.update({"font.size": 15})

    def mean(rows, key, scale=1.0):
        return [scale * rows[n][f"{key}_mean"] for n in ns]

    fig, ax = plt.subplots(2, 2, figsize=(10, 7.4))
    handles = []
    panels = [
        (ax[0, 0], "completion_rate", "Completion rate (%)", 100.0, False),
        (ax[0, 1], "t_claim_ms_mean", "Claim latency (ms, log)", 1.0, True),
        (ax[1, 0], "throughput_tps", "Throughput (tasks/min)", 60.0, False),
        (ax[1, 1], "agent_utilization", "Utilization (% working)", 100.0, False),
    ]
    for a, key, ylab, scale, logy in panels:
        l1, = a.plot(ns, mean(cen, key, scale), "s--", linewidth=2.4, markersize=9,
                     color="tab:red", label="centralized RTI")
        l2, = a.plot(ns, mean(dec, key, scale), "o-", linewidth=2.4, markersize=9,
                     color="tab:blue", label="decentralized")
        handles = [l2, l1]
        a.set_xlabel("robots N", fontsize=16)
        a.set_ylabel(ylab, fontsize=16)
        a.set_xticks(ns)
        a.tick_params(labelsize=14)
        if logy:
            a.set_yscale("log")
        elif scale == 100.0:
            a.set_ylim(0, 105)
    fig.legend(handles, ["decentralized", "centralized RTI"], loc="upper center",
               ncol=2, fontsize=15, frameon=False)
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    saved = []
    for ext in ("pdf", "png"):
        p = os.path.join(figs, f"coord_compare.{ext}")
        fig.savefig(p, bbox_inches="tight", dpi=150); saved.append(p)
    plt.close(fig)
    return saved


def main():
    ap = argparse.ArgumentParser(description="Centralized-RTI vs decentralized LF coordination")
    ap.add_argument("--centralized", default=os.path.join(REPO, "results"))
    ap.add_argument("--decentralized", default=os.path.join(REPO, "results", "decentral"))
    ap.add_argument("--out", default=os.path.join(REPO, "results"))
    ap.add_argument("--figs", default=os.path.join(REPO, "figures", "testbed"))
    args = ap.parse_args()
    cen, dec = load_agg(args.centralized), load_agg(args.decentralized)
    ns = sorted(set(cen) & set(dec))
    if not ns:
        raise SystemExit("no overlapping fleet sizes")
    os.makedirs(args.out, exist_ok=True)
    print(f"  {write_markdown(ns, cen, dec, args.out)}")
    print(f"  {write_latex(ns, cen, dec, args.out)}")
    for p in make_figure(ns, cen, dec, args.figs):
        print(f"  {p}")
    print(f"\nCompared N={ns} (centralized-RTI vs decentralized).")


if __name__ == "__main__":
    main()
