#!/usr/bin/env python3
"""
Generate ``docker-compose.<N>.yml`` for an N-robot emulation.

Each robot is its own container running the full per-robot stack
(LF federate ``f{i}`` + ROS-LF bridge + DSM node + agent), plus one
shared ``rti`` container and one ``metrics`` container. This mirrors the
per-Jetson deployment, just emulated as N containers on one host.

All sizing/timing comes from ``config/testbed.yaml`` (single source of truth).

Usage:
    python3 gen_compose.py 8                 # write docker-compose.8.yml
    python3 gen_compose.py --all             # one file per fleet_sizes entry
"""

import argparse
import os

import yaml

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
TESTBED_YAML = os.path.join(REPO, "config", "testbed.yaml")
IMAGE = "context-fabric-fed"


def load_cfg():
    with open(TESTBED_YAML) as f:
        return yaml.safe_load(f)


def fed_dir(n: int) -> str:
    """In-container path to the compiled federation of size N."""
    return f"/ros2_ws/fed-gen/coordinator_{n}/bin"


def common_env(cfg: dict) -> dict:
    return {
        "ROS_DOMAIN_ID": cfg["ros_domain_id"],
        "FASTRTPS_DEFAULT_PROFILES_FILE": "/ros2_ws/config/fastdds_udp_only.xml",
    }


def build_compose(cfg: dict, n: int) -> dict:
    fed = cfg["federation"]
    rti_host, rti_port, fed_id = fed["rti_host"], fed["rti_port"], fed["id"]
    timing = cfg["timing"]
    bind = "/ros2_ws/config/fastdds_udp_only.xml"

    # Shared volume mounts: live config + scripts (so we can tweak the spawner,
    # graph, and compose without rebuilding the image) and a logs dir that all
    # containers write run artifacts + overhead samples into.
    base_vols = [
        "./config:/ros2_ws/config",
        "./scripts:/ros2_ws/scripts",
        "./logs:/ros2_ws/logs",
    ]

    services = {}

    # --- RTI (shared logical-time coordinator) -----------------------------
    services["rti"] = {
        "image": IMAGE,
        "container_name": "cf_rti",
        "network_mode": "host",
        "command": [
            f"{fed_dir(n)}/RTI",
            "-i", fed_id,
            "-n", str(n),
            "-c", "init", "exchanges-per-interval", "10",
        ],
        "volumes": base_vols,
        "stdin_open": True,
        "tty": True,
    }

    # --- Robots (one container = one federate + bridge + dsm + agent) ------
    for i in range(1, n + 1):
        start_node = i - 1            # distinct perimeter (staging) start cells
        services[f"robot{i}"] = {
            "image": IMAGE,
            "container_name": f"cf_robot{i}",
            "network_mode": "host",
            "depends_on": ["rti"],
            "environment": {
                **common_env(cfg),
                "LF_RTI_HOST": rti_host,
                "LF_RTI_PORT": rti_port,
                "LF_FEDERATION_ID": fed_id,
            },
            "command": [
                "/ros2_ws/scripts/start_robot.sh",
                str(i),                                 # device_id / agent_id
                f"{fed_dir(n)}/federate__f{i}",         # this robot's federate
                str(rti_host),
                str(rti_port),
                fed_id,
                str(start_node),
                str(timing["step_time_s"]),
                str(timing["work_time_s"]),
            ],
            "volumes": base_vols,
            "stdin_open": True,
            "tty": True,
        }

    # --- Metrics aggregator (writes the per-run CSV/JSON summary) ----------
    services["metrics"] = {
        "image": IMAGE,
        "container_name": "cf_metrics",
        "network_mode": "host",
        "environment": {
            **common_env(cfg),
            "TESTBED_NUM_ROBOTS": n,
            # Seed is injected at `up` time via the host env CF_SEED (so one
            # compose file works across a multi-seed sweep); defaults to config.
            "TESTBED_SEED": "${CF_SEED:-%d}" % int(cfg["run"]["seed"]),
            "TESTBED_MODE": cfg.get("mode", "lf"),
            "TESTBED_CONFIG_NAME": f"{cfg.get('mode', 'lf')}_{n}robots",
        },
        "command": ["/ros2_ws/scripts/start_metrics.sh"],
        "volumes": base_vols,
        "stdin_open": True,
        "tty": True,
    }

    return {"services": services}


def write_compose(cfg: dict, n: int) -> str:
    out = os.path.join(REPO, f"docker-compose.{n}.yml")
    doc = build_compose(cfg, n)
    header = (
        f"# Auto-generated by scripts/gen_compose.py for N={n} robots.\n"
        f"# Source of truth: config/testbed.yaml. Do not hand-edit.\n"
    )
    with open(out, "w") as f:
        f.write(header)
        yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False, width=120)
    print(f"[gen_compose] wrote {out}  (rti + {n} robots + metrics)")
    return out


def main():
    cfg = load_cfg()
    ap = argparse.ArgumentParser(description="Generate docker-compose.<N>.yml")
    ap.add_argument("n", nargs="?", type=int, help="fleet size")
    ap.add_argument("--all", action="store_true", help="generate for every fleet_sizes entry")
    args = ap.parse_args()

    if args.all:
        for n in cfg["fleet_sizes"]:
            write_compose(cfg, n)
    elif args.n is not None:
        write_compose(cfg, args.n)
    else:
        ap.error("provide a fleet size N or --all")


if __name__ == "__main__":
    main()
