#!/usr/bin/env python3
"""
Generate ``docker-compose.ros.<N>.yml`` -- the ROS stack (robots + metrics) for
the ISOLATED-NETWORK testbed, designed to be merged with LF's generated
federation compose:

    docker compose -f fed-gen/coordinator_<N>/src-gen/docker-compose.yml \\
                   -f docker-compose.ros.<N>.yml  up

LF's compose puts RTI + federate__f1..fN on a user-defined bridge network named
``lf``. These ROS services declare no network, so when the two files are merged
they join that same default (``lf``) network -- each in its own container with
its own IP. Each robot's bridge reaches its federate by service-DNS
(``LF_FED_HOST=federate__f{i}``); the data plane (DDS topics) discovers over the
bridge via multicast (verified). ``cap_add: NET_ADMIN`` lets us apply per-
container ``tc netem`` later.

Usage: python3 gen_compose_ros.py 8
"""

import argparse
import os

import yaml

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
TESTBED_YAML = os.path.join(REPO, "config", "testbed.yaml")
IMAGE = "context-fabric-fed"


def load_cfg():
    with open(TESTBED_YAML) as f:
        return yaml.safe_load(f)


def ros_env(cfg):
    return {
        "ROS_DOMAIN_ID": cfg["ros_domain_id"],
        "RMW_IMPLEMENTATION": "rmw_fastrtps_cpp",
        "FASTRTPS_DEFAULT_PROFILES_FILE": "/ros2_ws/config/fastdds_udp_only.xml",
    }


def build(cfg, n):
    timing = cfg["timing"]
    # Absolute paths: this file is merged with LF's compose (whose dir becomes the
    # project dir), so relative mounts would resolve to the wrong place.
    vols = [f"{REPO}/config:/ros2_ws/config", f"{REPO}/scripts:/ros2_ws/scripts",
            f"{REPO}/logs:/ros2_ws/logs"]
    services = {}
    for i in range(1, n + 1):
        services[f"robot{i}"] = {
            "image": IMAGE,
            "container_name": f"cf_robot{i}",
            "cap_add": ["NET_ADMIN"],          # per-container netem on eth0
            "environment": {**ros_env(cfg), "LF_FED_HOST": f"federate__f{i}"},
            "command": ["/ros2_ws/scripts/start_robot_ros.sh", str(i), str(i - 1),
                        str(timing["step_time_s"]), str(timing["work_time_s"])],
            "volumes": vols,
            "stdin_open": True, "tty": True,
        }
    services["metrics"] = {
        "image": IMAGE,
        "container_name": "cf_metrics",
        "environment": {**ros_env(cfg),
                        "TESTBED_NUM_ROBOTS": n,
                        "TESTBED_SEED": "${CF_SEED:-%d}" % int(cfg["run"]["seed"]),
                        "TESTBED_MODE": "iso",
                        "TESTBED_CONFIG_NAME": f"iso_{n}robots"},
        "command": ["/ros2_ws/scripts/start_metrics.sh"],
        "volumes": vols,
        "stdin_open": True, "tty": True,
    }
    # (Stale baked bytecode is stripped in the federate Dockerfile by gen_lf.py,
    # so no runtime PYTHONPYCACHEPREFIX workaround is needed here.)
    # Opt-in live browser grid view (WITH_VIZ=1): publishes :8089 to the host.
    if os.environ.get("WITH_VIZ"):
        services["viz"] = {
            "image": IMAGE,
            "container_name": "cf_viz",
            "environment": {**ros_env(cfg), "FLEET_WEB_PORT": "8089"},
            "command": ["bash", "-lc",
                        "source /ros2_ws/install/setup.bash && python3 /ros2_ws/scripts/fleet_web.py"],
            "ports": ["8089:8089"],
            "volumes": vols,
            "stdin_open": True, "tty": True,
        }
    return {"services": services}


def write(cfg, n):
    out = os.path.join(REPO, f"docker-compose.ros.{n}.yml")
    header = (f"# Auto-generated by scripts/gen_compose_ros.py for N={n} (ROS stack).\n"
              f"# Merge with LF's compose: docker compose -f fed-gen/coordinator_{n}/src-gen/"
              f"docker-compose.yml -f docker-compose.ros.{n}.yml up\n")
    with open(out, "w") as f:
        f.write(header)
        yaml.safe_dump(build(cfg, n), f, sort_keys=False, default_flow_style=False, width=120)
    print(f"[gen_compose_ros] wrote {out}  ({n} robots + metrics on the lf network)")
    return out


def main():
    cfg = load_cfg()
    ap = argparse.ArgumentParser()
    ap.add_argument("n", type=int)
    args = ap.parse_args()
    write(cfg, args.n)


if __name__ == "__main__":
    main()
