#!/usr/bin/env python3
"""
Generate ``docker-compose.central.<N>.yml`` -- the CENTRALIZED-coordination
baseline for the central-vs-distributed comparison.

Same robots, agents, metrics and task workload as the distributed testbed
(``gen_compose_ros.py``); the ONLY difference is the coordination topology:

  * distributed (Context-Fabric): N federates, robot i -> federate__f{i}
    (a replicated coordinator per robot, all-to-all proposal mesh + gossip).
  * centralized (this file): ONE federate (``federate__f1``) serves ALL N
    robots -- every robot's bridge + node-lock socket targets
    ``LF_FED_HOST=federate__f1`` / ``LF_FED_PORT=9001``.

Holding the coordinator implementation constant (the same LF CoordinatorFederate
in both) isolates the single variable under study: one central coordinator vs.
N distributed replicas. Merge with LF's 1-federate compose:

    docker compose -f fed-gen/coordinator_1/src-gen/docker-compose.yml \\
                   -f docker-compose.central.<N>.yml  up

Usage: python3 gen_compose_central.py 8
"""

import argparse
import os

import yaml

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
TESTBED_YAML = os.path.join(REPO, "config", "testbed.yaml")
IMAGE = "context-fabric-fed"
CENTRAL_FED = "federate__f1"   # the single shared coordinator
CENTRAL_PORT = "9001"


def load_cfg():
    with open(TESTBED_YAML) as f:
        return yaml.safe_load(f)


def ros_env(cfg):
    return {
        "ROS_DOMAIN_ID": cfg["ros_domain_id"],
        "RMW_IMPLEMENTATION": "rmw_fastrtps_cpp",
        "FASTRTPS_DEFAULT_PROFILES_FILE": "/ros2_ws/config/fastdds_udp_only.xml",
    }


def build(cfg, n):
    timing = cfg["timing"]
    vols = [f"{REPO}/config:/ros2_ws/config", f"{REPO}/scripts:/ros2_ws/scripts",
            f"{REPO}/logs:/ros2_ws/logs"]
    services = {}
    for i in range(1, n + 1):
        services[f"robot{i}"] = {
            "image": IMAGE,
            "container_name": f"cf_robot{i}",
            "cap_add": ["NET_ADMIN"],
            # Every robot targets the ONE central federate (vs federate__f{i}).
            "environment": {**ros_env(cfg),
                            "LF_FED_HOST": CENTRAL_FED, "LF_FED_PORT": CENTRAL_PORT},
            "command": ["/ros2_ws/scripts/start_robot_ros.sh", str(i), str(i - 1),
                        str(timing["step_time_s"]), str(timing["work_time_s"])],
            "volumes": vols,
            "stdin_open": True, "tty": True,
        }
    services["metrics"] = {
        "image": IMAGE,
        "container_name": "cf_metrics",
        "environment": {**ros_env(cfg),
                        "TESTBED_NUM_ROBOTS": n,
                        "TESTBED_SEED": "${CF_SEED:-%d}" % int(cfg["run"]["seed"]),
                        "TESTBED_MODE": "central",
                        "TESTBED_CONFIG_NAME": f"central_{n}robots"},
        "command": ["/ros2_ws/scripts/start_metrics.sh"],
        "volumes": vols,
        "stdin_open": True, "tty": True,
    }
    # Single central federate: dodge any stale baked bytecode (see gen_compose_ros).
    services[CENTRAL_FED] = {"environment": {"PYTHONPYCACHEPREFIX": "/tmp/pyc"}}
    return {"services": services}


def write(cfg, n):
    out = os.path.join(REPO, f"docker-compose.central.{n}.yml")
    header = (f"# Auto-generated by scripts/gen_compose_central.py for N={n} "
              f"(CENTRALIZED baseline: {n} robots -> 1 shared federate {CENTRAL_FED}).\n"
              f"# Merge: docker compose -f fed-gen/coordinator_1/src-gen/docker-compose.yml "
              f"-f docker-compose.central.{n}.yml up\n")
    with open(out, "w") as f:
        f.write(header)
        yaml.safe_dump(build(cfg, n), f, sort_keys=False, default_flow_style=False, width=120)
    print(f"[gen_compose_central] wrote {out}  ({n} robots -> 1 central federate)")
    return out


def main():
    cfg = load_cfg()
    ap = argparse.ArgumentParser()
    ap.add_argument("n", type=int)
    args = ap.parse_args()
    write(cfg, args.n)


if __name__ == "__main__":
    main()
