#!/usr/bin/env python3
"""
Generate a grid warehouse graph (``config/warehouse_graph.yaml``).

The default testbed graph (a 5x5, 25-node grid) gridlocks well before 16
robots. This generator emits an ``rows x cols`` 4-connected grid sized to keep
even the largest fleet at warehouse-like density (~4-5 %), matching the thesis
simulation's assumptions.

Node typing (kept deliberately simple):
  * perimeter cells  -> ``staging``  (robot start / idle / post-work clearing)
  * interior cells   -> ``work``     (task targets the spawner picks from)

Reads sizing from ``config/testbed.yaml`` (``graph.rows`` / ``graph.cols``)
unless overridden on the command line.

Usage:
    python3 gen_graph.py                       # use testbed.yaml sizing
    python3 gen_graph.py --rows 20 --cols 20
    python3 gen_graph.py --out config/warehouse_graph.yaml
"""

import argparse
import os

import yaml

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
TESTBED_YAML = os.path.join(REPO, "config", "testbed.yaml")


def load_cfg():
    with open(TESTBED_YAML) as f:
        return yaml.safe_load(f)


def build_graph(rows: int, cols: int, border_type: str, interior_type: str) -> dict:
    nodes = {}
    for r in range(rows):
        for c in range(cols):
            nid = r * cols + c
            is_border = (r == 0 or r == rows - 1 or c == 0 or c == cols - 1)
            nodes[nid] = {
                "x": c,
                "y": r,
                "type": border_type if is_border else interior_type,
            }

    edges = []
    for r in range(rows):
        for c in range(cols):
            nid = r * cols + c
            if c + 1 < cols:                       # horizontal
                edges.append({"from": nid, "to": nid + 1, "weight": 1.0})
            if r + 1 < rows:                       # vertical
                edges.append({"from": nid, "to": nid + cols, "weight": 1.0})

    return {"nodes": nodes, "edges": edges}


def main():
    cfg = load_cfg()
    g = cfg.get("graph", {})
    ap = argparse.ArgumentParser(description="Generate a grid warehouse graph")
    ap.add_argument("--rows", type=int, default=g.get("rows", 20))
    ap.add_argument("--cols", type=int, default=g.get("cols", 20))
    ap.add_argument("--border-type", default=g.get("border_type", "staging"))
    ap.add_argument("--interior-type", default=g.get("interior_type", "work"))
    ap.add_argument("--out", default=os.path.join(REPO, g.get("path", "config/warehouse_graph.yaml")))
    args = ap.parse_args()

    graph = build_graph(args.rows, args.cols, args.border_type, args.interior_type)
    n_nodes = len(graph["nodes"])
    n_work = sum(1 for m in graph["nodes"].values() if m["type"] == args.interior_type)

    header = (
        f"# Auto-generated by scripts/gen_graph.py  ({args.rows}x{args.cols} grid, "
        f"{n_nodes} nodes, {n_work} work cells)\n"
        f"# Perimeter = {args.border_type}, interior = {args.interior_type}.\n"
        f"# Edit config/testbed.yaml (graph.rows/cols) and regenerate, don't hand-edit.\n"
    )
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(header)
        yaml.safe_dump(graph, f, sort_keys=True, default_flow_style=None)

    print(f"[gen_graph] wrote {args.out}: {args.rows}x{args.cols} = {n_nodes} nodes "
          f"({n_work} work, {n_nodes - n_work} staging), {len(graph['edges'])} edges")


if __name__ == "__main__":
    main()
